### PR TITLE
LIGO unmodeled search for gravitational wave echoes

### PR DESCRIPTION
**Pull request by astroclark**

### CODE REVIEW

**Comment by astroclark** [comment]
Evidently i need someone else to make this repo/registry public.  Update to follow.

**Comment by astroclark** [comment]
The registry for this image should now be public, I do not expect further failures but I'm not sure how to re-run the check

**Comment by djw8605** [comment]
The check seems to have passed?

**Comment by astroclark** [comment]
Looks good now - it had previously failed.  Thanks

**Pull request merged**
