### PR TITLE
feat: Add mario-maypde images

### PR DESCRIPTION
**Pull request by kratsg**
We have a bunch of helpful docker images for doing MC generation, simulation, and analysis: https://github.com/scipp-atlas/mario-mapyde . These are useful in a lot of situations, but in particular, would like to sync via cvmfs to use via condor OSG for the snowmass connect project.

### CODE REVIEW

**Comment by kratsg** [comment]
Seems the manifest check is failing, but it works fine for me locallly

```
$ docker manifest inspect ghcr.io/scipp-atlas/mario-mapyde/madgraph:latest
{
	"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
	"schemaVersion": 2,
	"config": {
		"mediaType": "application/vnd.docker.container.image.v1+json",
		"digest": "sha256:4279ab383eab9b37847a2b75ee642b675067ef82f484e1a4f010ac78c884d35b",
		"size": 13442
	},
```

**Comment by hzhu16** [comment]
Solved in PR 353

**Comment by kratsg** [comment]
Seems superseded by #353. Didn't realize. Ok.

**Pull request closed without merging**
