### PR TITLE
ENH add lsst desc stackvana image

### PR DESCRIPTION
**Pull request by beckermr**
Note that this image uses both ENV and ENTRYPOINT commands in the dockerfile and those need to be preserved when it is converted to singularity.

cc @esheldon @tmcclintock

### CODE REVIEW

**Comment by rynge** [comment]
@beckermr I have merged this one, but note that ENV and ENTRYPOINTs are never preserved in this system. The HTCondor job is started inside the container so therefore ENTRYPOINT is ignored. If you have specific ENV requirements, they can be set in the job as well.

**Comment by beckermr** [comment]
@ryng are the ENV and ENTRYPOINT directives going to be preserved?

It said in the documentation that they would be ignored.

**Comment by beckermr** [comment]
So there is no way around this? The docs sounded optimistic.

**Comment by beckermr** [comment]
I’ll have to adjust the container then which will require me to resubmit it. How often do you sync the latest tags from dockerhub? The containers under those can shift.

**Comment by djw8605** [comment]
The docker tags are sync'd every ~15 minutes.  But, due to lots of layers of caching, it can take an additional 5-60 minutes for the changes to be reflected on a client.

**Comment by rynge** [comment]
And no need to resubmit. One it is registered, you just need to push to DockerHub for us to detect the changes and pull it down to CVMFS again.

**Pull request merged**
