### PR TITLE
- added new image for Gluex vo (richard.t.jones@uconn.edu)

### PR DESCRIPTION
**Pull request by rjones30**

### CODE REVIEW

**Comment by bbockelm** [comment]
Hi Richard - one small favor to ask.  In the Dockerfile for this image, can you download the software via HTTPS or do a checksum verification after downloading via HTTP?

Many thanks!

**Comment by rjones30** [comment]
Brian,

This is done, everything looks to be in good shape, will submit some jobs
shortly. We recently turned off my gwms frontend daemon (the one configured
with the frontend.xml config file, not the condor frontends) to use one
that is being operated by central OSG services on our behalf. Is there
anything I need to do to change my configuration on my frontend schedd and
collector hosts to recognize the new location?

-Richard J.

**Comment by bbockelm** [comment]
There shouldn't be any changes you have to do on your side, but it's worth to double-check with an email to Edgar.  He should also be able to provide information about how to request execution of a job inside a particular Singularity container.  I think this page _may_ apply: https://support.opensciencegrid.org/support/solutions/articles/12000024676-singularity-containers

**Comment by rjones30** [comment]
Brian,

That is one of the main pages I am working from. Thanks for your help.

-Richard J.

**Pull request merged**
