### PR TITLE
Add AMNH PipeMaster Image

### PR DESCRIPTION
**Pull request by ssgituser**

### CODE REVIEW

**Comment by ssgituser** [comment]
Please advise as to why the checks are failing. I would like to get the amnh/osgimages:pipemaster_initial image into CVMFS/singularity.

**Comment by djw8605** [comment]
Hi.  The failures were not for your container.  Also, I cannot re-create the test because of some github error.  I will merge this because your container was good.

**Comment by ssgituser** [comment]
Thank you.


--
______________________________________________
Sajesh Singh
Manager, Systems and Scientific Computing
American Museum of Natural History
200 Central Park West
New York, NY 10024

(O) (212) 313-7263
(C) (917) 763-9038
(E) ssingh@amnh.org

________________________________

**Comment by ssgituser** [comment]
Derek,
  How long after the commit does it take for the image to be visible in CVMFS?

-Sajesh-


--
______________________________________________
Sajesh Singh
Manager, Systems and Scientific Computing
American Museum of Natural History
200 Central Park West
New York, NY 10024

(O) (212) 313-7263
(C) (917) 763-9038
(E) ssingh@amnh.org

________________________________

**Comment by djw8605** [comment]
There are a lot of caches between the origin and most clients.  It could vary from between a few minutes, to ~1 hour.

**Pull request merged**
