### PR TITLE
Add Ligo Virgo Kagra Container for LALSuite

### PR DESCRIPTION
**Pull request by drshawnkwang**
Add Ligo Virgo Kagra Containers to OSG for CVMFS publishing. This PR specifically adds containers for LALSuite.

### CODE REVIEW

**Comment by drshawnkwang** [comment]
Glob pattern is for all containers associated with lalsuite, which can be seen at https://git.ligo.org/lscsoft/lalsuite/container_registry (public). Total number of containers is currently 26.

Let me know if that glob pattern works for this publisher.

**Comment by djw8605** [comment]
I think globs only work on tags. 

-Derek

**Comment by drshawnkwang** [comment]
Sorry about that, I was not 100% clear when I asked you the other day about glob patterns in this file. I'll refactor this PR later today and include a few of latest the versions. Thanks for the info.

**Comment by drshawnkwang** [comment]
@djw8605 - I've modified the PR to include a few of the latest versions of LALSuite. Let me know if this works.

**Pull request merged**
