### PR TITLE
relugzosiraba/kwant_adaptive:v1

### PR DESCRIPTION
**Pull request by relugzosiraba**
Update docker_images.txt

### CODE REVIEW

**Comment by djw8605** [comment]
Hi,

It appears that your pull request includes every commit since september of last year.   What docker image are you trying to add?  Just let me know and I can redo the pull request.

Closing this pull request for now.
-Derek

**Comment by relugzosiraba** [comment]
Hi Derek,

I chose the base as "Add-wn-synergia2latest" and compare as "master". If I
did it oppositely (as shown here
<https://github.com/opensciencegrid/cvmfs-singularity-sync/compare/master...Add-wn-synergia2latest?expand=1>
), I get the following message: "There isn’t anything to compare. master is
up to date with all commits from Add-wn-synergia2latest. Try switching the
base for your comparison.". How could I do it correctly?

I am trying to add relugzosiraba/kwant_adaptive:v1

Thanks for your help!

Barış

**Comment by djw8605** [comment]
Hi,

I created a pull request with your requested changes:
https://github.com/opensciencegrid/cvmfs-singularity-sync/pull/215

The usual flow for adding a image is:
1. Create a personal fork of the cvmfs-singularity-repo
2. Make the change to docker_images.txt in your personal repo.
3. Commit and push the changes to your personal repo.
4. Create the pull request against this upstream repo.

**Comment by relugzosiraba** [comment]
Thanks!

**Pull request closed without merging**
