### PR TITLE
Add a NOvA container being developed for NOvA/T2K joint fit

### PR DESCRIPTION
**Pull request by cjbackhouse**

### CODE REVIEW

**Comment by cjbackhouse** [comment]
I wasn't able to understand what checks failed by looking at the log. Could someone please advise?

**Comment by djw8605** [comment]
Could you resolve the conflicts real quick.  Hopefully that will kick off a successful github build.

**Comment by cjbackhouse** [comment]
I think I just did, but it's still failing. But the error output is now listing repos different to the one I added?

**Comment by djw8605** [comment]
Ok, your image looks good.  Merging!

**Pull request merged**
